### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by driskerr** [sophlie996/intro-data-capstone-biodiversity#9]
Overall, great job! You have a clear mastery of the python syntax and language and your findings are on point! Plus, your slides are well-designed and well-structured with a good balance of text and visual information (i.e. good use of a table on "Likelihood of Species Endangerment" slide). There is a natural flow of information in your presentation and I appreciate the use of cute animal images to keep things engaging/lively. 

In your code, you demonstrate a great understanding of how to manipulate and explore data frames. My main code comments were some minor recommendations for less wordy/more concise code. This can be achieved by referring to just the dataframe or column name when appropriate or limiting your use of lambda functions in horizontal dataframe calculations. I appreciated when you went above-and-beyond in your code when using Python 3 print syntax and when you reported your findings by concatenating the variables holding your answers into string sentences.

Also, I recommend that use as precise decimals as possible. Your calculation of sample size for the foot-and-mouth disease study was slightly off because of the decimal precision of your minimum detectable effect. I encourage you to play around with the calculator here to test the impact of various decimal levels.

**Comment by annadouv88** [comment]
Thank you so much for your comments! They were very helpful. Thanks for letting me know about the decimal precision as well, I wasn't aware how much it affected the calculation. I'm glad you appreciated the presentation, I had fun with it :)
